import { groupByCollection } from '@/lib/services/nft.service';
import { MOCK_ETH_USD } from '@/lib/mock/portfolio';
import type { NftCollection, NftItem } from '@/types';

/**
 * Demo NFTs for the gallery.
 *
 * Collections, contract addresses, and OpenSea paths are the real ones, so a
 * card's link lands on the collection it claims to be from. Artwork is local
 * (`/public/mock`, generated by `scripts/generate-mock-art.mjs`) rather than a
 * remote thumbnail: a placeholder host can go away, and a gallery of broken
 * images is a worse demo than a gallery of abstract ones.
 */

/** Fixed acquisition dates, kept as UTC literals so the demo never depends on the clock. */
function acquired(year: number, month: number, day: number): number {
  return Date.UTC(year, month - 1, day);
}

interface MockCollection {
  address: `0x${string}`;
  name: string;
  /** Collection floor in ETH, the unit marketplaces quote it in. */
  floorEth: number;
  /** Local artwork prefix; each token appends its own index. */
  artPrefix: string;
  tokens: readonly {
    tokenId: string;
    name: string;
    description: string;
    acquiredAt: number;
  }[];
}

const COLLECTIONS: readonly MockCollection[] = [
  {
    address: '0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D',
    name: 'Bored Ape Yacht Club',
    floorEth: 12.4,
    artPrefix: 'bayc',
    tokens: [
      {
        tokenId: '8817',
        name: 'Bored Ape #8817',
        description: 'A navy-fur ape with a sailor hat, held since the 2024 drawdown.',
        acquiredAt: acquired(2024, 3, 12)
      },
      {
        tokenId: '3129',
        name: 'Bored Ape #3129',
        description: 'Golden fur, laser eyes, and a smirk that survived two bear markets.',
        acquiredAt: acquired(2023, 11, 4)
      },
      {
        tokenId: '7403',
        name: 'Bored Ape #7403',
        description: 'Trippy fur with a party hat, the last one bought near the local top.',
        acquiredAt: acquired(2022, 1, 27)
      }
    ]
  },
  {
    address: '0xBd3531dA5CF5857e7CfAA92426877b022e612cf8',
    name: 'Pudgy Penguins',
    floorEth: 9.85,
    artPrefix: 'pudgy',
    tokens: [
      {
        tokenId: '5412',
        name: 'Pudgy Penguin #5412',
        description: 'Ice-cube background with a bow tie; the collection that kept its floor.',
        acquiredAt: acquired(2024, 6, 8)
      },
      {
        tokenId: '2201',
        name: 'Pudgy Penguin #2201',
        description: 'Pink beanie, tucked away and never listed.',
        acquiredAt: acquired(2023, 8, 19)
      },
      {
        tokenId: '7891',
        name: 'Pudgy Penguin #7891',
        description: 'Green scarf on a night-blue backdrop.',
        acquiredAt: acquired(2025, 2, 2)
      }
    ]
  },
  {
    address: '0xED5AF388653567Af2F388E6224dC7C4b3241C544',
    name: 'Azuki',
    floorEth: 5.62,
    artPrefix: 'azuki',
    tokens: [
      {
        tokenId: '2231',
        name: 'Azuki #2231',
        description: 'Red robe, elemental background, from the original 2022 mint.',
        acquiredAt: acquired(2022, 1, 12)
      },
      {
        tokenId: '6604',
        name: 'Azuki #6604',
        description: 'A quiet one: no headwear, plain background, held for the art.',
        acquiredAt: acquired(2024, 9, 30)
      }
    ]
  }
];

/** Local artwork for the token at a given global index, e.g. `/mock/nft-03.svg`. */
function artFor(index: number): string {
  return `/mock/nft-${String(index + 1).padStart(2, '0')}.svg`;
}

/** OpenSea deep link for a token on a chain, matching what the NFT reader builds. */
function openseaUrl(address: string, tokenId: string): string {
  return `https://opensea.io/assets/ethereum/${address}/${tokenId}`;
}

/**
 * The demo gallery: eight tokens across three Ethereum collections.
 *
 * Floors are quoted in ETH and converted at {@link MOCK_ETH_USD}, so the USD
 * figures agree with the token side of the demo portfolio instead of implying a
 * second, different ether price.
 */
export function createMockNfts(): NftItem[] {
  const items: NftItem[] = [];
  let index = 0;

  for (const collection of COLLECTIONS) {
    for (const token of collection.tokens) {
      items.push({
        chainId: 1,
        contractAddress: collection.address,
        tokenId: token.tokenId,
        id: `1:${collection.address.toLowerCase()}:${token.tokenId}`,
        collectionName: collection.name,
        name: token.name,
        description: token.description,
        imageUrl: artFor(index),
        floorPriceNative: collection.floorEth,
        floorPriceUsd: collection.floorEth * MOCK_ETH_USD,
        openseaUrl: openseaUrl(collection.address, token.tokenId),
        spamClassification: 'not_spam',
        acquiredAt: token.acquiredAt
      });
      index += 1;
    }
  }

  return items;
}

/** The demo gallery rolled up per collection, using the reader's own grouping. */
export function createMockNftCollections(): NftCollection[] {
  return groupByCollection(createMockNfts());
}
